2024-07-27 13:11:05,680 INFO    MainThread:68747 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-07-27 13:11:05,681 INFO    MainThread:68747 [wandb_setup.py:_flush():76] Configure stats pid to 68747
2024-07-27 13:11:05,681 INFO    MainThread:68747 [wandb_setup.py:_flush():76] Loading settings from /home/lindsay/.config/wandb/settings
2024-07-27 13:11:05,683 INFO    MainThread:68747 [wandb_setup.py:_flush():76] Loading settings from /mnt/d/GitHub/nd0821-c2-build-model-workflow-exercises/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/solution/check_data/wandb/settings
2024-07-27 13:11:05,684 INFO    MainThread:68747 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'run_group': 'dev', 'project': 'exercise_14'}
2024-07-27 13:11:05,685 INFO    MainThread:68747 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-27 13:11:05,685 WARNING MainThread:68747 [wandb_setup.py:_flush():76] Could not save program above cwd: /home/lindsay/miniconda3/envs/mlflow-d2c8f82fbae4739797a400248dc26c5b3a522318/bin/pytest
2024-07-27 13:11:05,686 INFO    MainThread:68747 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program_abspath': '/home/lindsay/miniconda3/envs/mlflow-d2c8f82fbae4739797a400248dc26c5b3a522318/bin/pytest', 'program': '/home/lindsay/miniconda3/envs/mlflow-d2c8f82fbae4739797a400248dc26c5b3a522318/bin/pytest'}
2024-07-27 13:11:05,687 INFO    MainThread:68747 [wandb_init.py:_log_setup():526] Logging user logs to /mnt/d/GitHub/nd0821-c2-build-model-workflow-exercises/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/solution/check_data/wandb/run-20240727_131105-lcabp866/logs/debug.log
2024-07-27 13:11:05,687 INFO    MainThread:68747 [wandb_init.py:_log_setup():527] Logging internal logs to /mnt/d/GitHub/nd0821-c2-build-model-workflow-exercises/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/solution/check_data/wandb/run-20240727_131105-lcabp866/logs/debug-internal.log
2024-07-27 13:11:05,688 INFO    MainThread:68747 [wandb_init.py:init():566] calling init triggers
2024-07-27 13:11:05,688 INFO    MainThread:68747 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-07-27 13:11:05,688 INFO    MainThread:68747 [wandb_init.py:init():616] starting backend
2024-07-27 13:11:05,689 INFO    MainThread:68747 [wandb_init.py:init():620] setting up manager
2024-07-27 13:11:05,695 INFO    MainThread:68747 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-07-27 13:11:05,696 INFO    MainThread:68747 [wandb_init.py:init():628] backend started and connected
2024-07-27 13:11:05,706 INFO    MainThread:68747 [wandb_init.py:init():720] updated telemetry
2024-07-27 13:11:05,825 INFO    MainThread:68747 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-07-27 13:11:06,131 INFO    MainThread:68747 [wandb_run.py:_on_init():2262] communicating current version
2024-07-27 13:11:06,246 INFO    MainThread:68747 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.17.5 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-07-27 13:11:06,247 INFO    MainThread:68747 [wandb_init.py:init():804] starting run threads in backend
2024-07-27 13:11:07,907 INFO    MainThread:68747 [wandb_run.py:_console_start():2241] atexit reg
2024-07-27 13:11:07,909 INFO    MainThread:68747 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-07-27 13:11:07,910 INFO    MainThread:68747 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-07-27 13:11:07,910 INFO    MainThread:68747 [wandb_run.py:_redirect():2186] Redirects installed.
2024-07-27 13:11:07,915 INFO    MainThread:68747 [wandb_init.py:init():847] run started, returning control to user process
2024-07-27 13:11:13,935 WARNING MsgRouterThr:68747 [router.py:message_loop():77] message_loop has been closed
